### ISSUE TITLE
Too many levels are displayed (:maxdepth:)

### ISSUE THREAD

**Issue by FlorianT03** [TYPO3-Documentation/render-guides#103]
In the php rendered version, several levels are displayed in the table of contents despite :maxdepth: 1. Normally only one level should be displayed

Code:

```
**Table of Contents**

..  toctree::
    :maxdepth: 1

    ConfigurationOverview
    Glossary
    ConfigurationFiles
    ConfigurationModule/Index
    FeatureToggles
    GlobalVariables
    Typo3ConfVars/Index
    Typo3Information
    TypoScript/Index
    UserSettingsConfiguration/Index
    Yaml/Index
```

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us//Configuration/Index.html

**Comment by linawolf** [comment]
This should be resolved with https://github.com/phpDocumentor/guides/pull/799
