### ISSUE TITLE
Code Highlighting alias

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/render-guides#164]
@brotkrueml, The following code blocks cause warnings in the Changelog. Should we create aliases? It might in part also be due to case, maybe we could interpret them independent of case?

app.WARNING: Language "JavaScript" is not available to highlight code
app.WARNING: Language "TypoScript" is not available to highlight code
app.WARNING: Language "mysql" is not available to highlight code
app.WARNING: Language "HTML" is not available to highlight code

**Comment by brotkrueml** [comment]
Thanks, maybe just lowercasing them in the Twig extension is enough.

Is "mysql" really highlighted in the old way? This should be considered an error and changed to "sql".

**Comment by brotkrueml** [comment]
In which manuals are they? Especially the "mysql" one?

**Comment by linawolf** [comment]
In the changelog

**Comment by linawolf** [comment]
I am currently debugging the changelog to remove the warnings in the old sphinx. Lets see if it pops up there

**Comment by linawolf** [comment]
mysql is actually one if the supported lexers: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference/Code/Codeblocks.html#writing-rest-codeblocks-available-lexers

**Comment by brotkrueml** [comment]
> mysql is actually one if the supported lexers: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference/Code/Codeblocks.html#writing-rest-codeblocks-available-lexers

I would avoid it to add those sql aliases. When on it, please adjust it. It makes no sense to have a mysql (or sqlite3 or ...) IMHO. And mysql also means mariadb? So, when speaking of dialects, mariadb has features mysql haven't and vice versa. So this makes altogether no sense for me. Also when seeing, there is no separate highlighter for that.

Would also avoid the lowercase thingy after thinking about it. In the docs it is also lowercase, so I see uppercase letters as an error - we should not support wrong written languages.

**Comment by linawolf** [comment]
We currently have the goal to offer anything that sphinx could do. We can deprecate the usage of uppercase if you like, though I would say this is just making it unnecessary hard for ppl

**Comment by brotkrueml** [comment]
I disagree. We have a new highlighter. Not everything is available ("mysql"). And if it is used wrongly (uppercase), then this should be a warning. And: These are edge cases. "none" and "text" are special as they are used widely, therefore aliases are okay.

And I won't start a new package with deprecations.

**Comment by linawolf** [comment]
I think better warnings at least stating in which file the code-block was found, are a nessecarity then

**Comment by linawolf** [comment]
Yes but good luck in searching "JavaScript" or "mysql" in the changelog. How can we provide the context

**Comment by brotkrueml** [comment]
Grr, got it, have that as branch, but not merged yet:
https://github.com/brotkrueml/twig-codehighlight/tree/add-context

AFAIK the context was empty, therefore no value for us currently.

**Comment by brotkrueml** [comment]
Yup, this is currently logged when using the context:

    `[2023-12-12T20:17:32.233216+01:00] app.WARNING: Language "mysql" is not available to highlight code {"node":{"phpDocumentor\\Guides\\Nodes\\CodeNode":[]},"env":{"phpDocumentor\\Guides\\RenderContext":[]},"showLineNumbers":false,"startWithLineNumber":1} []`

**Comment by linawolf** [comment]
I renamed them in core now
