### ISSUE TITLE
Current state in menu not available

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/render-guides#222]
When navigating to a menu entry, that menu entry should have the "current" class assigned:

sitemap-level.html.twig:
```html
<li class="toctree-l{{ menuEntry.level }} {%- if menuEntry.isInRootline %} current {% endif %}">
```

menu-level.html.twig may be also affected.

However, it is not:

![Bildschirmfoto vom 2023-12-18 10-17-56](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/99c4b4e3-c377-4aea-a9fc-dd8fae29ce00)

**Comment by linawolf** [comment]
Yes, I am currently waiting for https://github.com/phpDocumentor/guides/pull/759 to be merged
