### ISSUE TITLE
Definition list with textrole in term does not work

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/render-guides#225]
As can be seen here:

https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Conditions/Index.html#sitelanguage

**Comment by linawolf** [comment]
@brotkrueml this should render now without issue. Can you confirm?

**Comment by brotkrueml** [comment]
Yup, looks good:

![Bildschirmfoto vom 2023-12-23 14-50-32](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/bf646c8d-1abe-4545-8254-88b3a6a28240)
