### ISSUE TITLE
Wrong display of the list of release versions

### ISSUE THREAD

**Issue by FlorianT03** [TYPO3-Documentation/render-guides#288]
When I click on the "+" of "Introduction" on the left, for example, a list of all the release versions for the docs opens automatically. However, this should not happen, only the sub-items for the introductions should appear; this also applies to the other items such as "Quick start" etc.

https://docs.typo3.org/p/georgringer/news/draft/en-us/Index.html

PS: Apparently a single click is enough to display the list of releases, I accidentally clicked on an empty part of the website and the list of releases appeared.

**Comment by brotkrueml** [comment]
Yup, this is known. The click handler seems to be registered to the whole document instead of only the version selector.
