### ISSUE TITLE
Styling mistake for the Image subtitle

### ISSUE THREAD

**Issue by FlorianT03** [TYPO3-Documentation/render-guides#289]
At the bottom, below the bottom image, the gap between the image and the "4.Save the plugin." is too large.

Compare:
https://docs.typo3.org/p/georgringer/news/draft/en-us/QuickStart/CreateRecords.html
https://docs.typo3.org/p/georgringer/news/main/en-us/QuickStart/CreateRecords.html

**Comment by linawolf** [comment]
I think it looks better with the larger gap in most cases.

**Comment by brotkrueml** [comment]
The image has a large offset (i added a border):

![image](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/0eb21065-4211-4726-9b15-aac7baa544e9)

So, nothing we can do about it.

**Comment by brotkrueml** [comment]
But: The class is not recognised: The "with-shadow" is not considered. This may be a bug.

**Comment by linawolf** [comment]
yes, looking into the shadow
