### ISSUE TITLE
No Content inside the tip box and the attention box

### ISSUE THREAD

**Issue by FlorianT03** [TYPO3-Documentation/render-guides#290]
The box with the tip is without content:
https://docs.typo3.org/p/georgringer/news/draft/en-us/Tutorials/ExtendNews/Hooks/Index.html
https://docs.typo3.org/p/georgringer/news/draft/en-us/Administration/Migration/MigrationFromTtNews/Index.html
https://docs.typo3.org/p/georgringer/news/draft/en-us/Reference/TypoScript/PluginSettings.html

The box with the Attention is also without content: https://docs.typo3.org/p/georgringer/news/draft/en-us/Tutorials/ExtendNews/ProxyClassGenerator/Index.html

**Comment by linawolf** [comment]
This is already resolved. I triggered re-rendering and all boxes work now.
