### ISSUE TITLE
Version selector removes `.0` in `x.0` release

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/render-guides#317]
When defining a `version="3.0"` in the guides.xml, the version selector just displays `3` instead of `3.0` when rendered locally:

![Bildschirmfoto vom 2024-01-25 08-07-54](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/344e834a-cf47-49a5-b476-efa0bb957100)

**Comment by linawolf** [comment]
This seems to be a bug in the guides, the string delivered to the template already contains "3" instead of "3.0"

**Comment by linawolf** [comment]
Yep, it is a problem in the guides and I could not find a solution :-( https://github.com/phpDocumentor/guides/issues/829

**Comment by linawolf** [comment]
Resolved by https://github.com/phpDocumentor/guides/pull/836
