### ISSUE TITLE
Previous & Next buttons

### ISSUE THREAD

**Issue by jaapio** [TYPO3-Documentation/render-guides#35]
The sphinx documentation has previous and next buttons to navigate between pages.  

What should we do with them? Do we want to implement this?

**Comment by linawolf** [comment]
Yes I would like to keep them, they are useful in Tutorials that you want to read from Start to end

**Comment by garvinhicking** [comment]
+1 on that. When learning for Certifications etc., easily going through chapters has always been very helpful to me.
