### ISSUE TITLE
Clicking on one tab should also switch to the same tab of every tab group

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/render-guides#353]
In the Sphinx-based rendering, when I switch to a tab, all other tabs of every tab group switch to this tab (if available).

This is especially useful, for example, on the commands page: when switching to "Legacy installation", the tab is switched for every group. So the user does not have to switch manually every tab group.

With PHP-based rendering the other tab groups remain on the first tab as active.

**Comment by tmotyl** [comment]
@linawolf please add a link with examlple from new and old rendering

**Comment by linawolf** [comment]
Old:
https://docs.typo3.org/m/typo3/docs-how-to-document/1.0/en-us/WritingReST/Reference/Content/Tabs.html

New
https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference/Content/Tabs.html
