### ISSUE TITLE
Classes of a figure should only by applied to an image

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/render-guides#371]
Example:

    .. figure:: ../Images/Settings.png
       :alt: The Settings screen of the Admin Panel
       :class: with-border

       The Settings screen of the Admin Panel

results in:

![Bildschirmfoto vom 2024-03-01 13-08-06](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/558e5479-eb2b-493e-9228-04e9464d6790)

Instead, the caption should not be surrounded with the border, just the image tag, like in the old rendering:

![Bildschirmfoto vom 2024-03-01 13-09-22](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/4a602bfb-ad9d-4baa-bd79-9aa18939e563)

**Comment by linawolf** [comment]
I dont see it as a bug, I did this on intend. Now the caption belongs to the image while before it was laying somewhere in the empty room

**Comment by brotkrueml** [comment]
Hmm, I used the with-border class mainly to "frame" the image, not the whole figure (to look better). For example here:
https://docs.typo3.org/p/brotkrueml/typo3-matomo-widgets/3.0/en-us/Widgets/Index.html#actions-per-day

When we leave it that way, I have to process the image manually to apply a border or to make the screenshot pixel-accurate.

**Comment by garvinhicking** [comment]
Personally, I'd say leaving the caption visually outside the box looks better. Did you ever talk about maybe positioning the caption horizontally below the image or to the right? Then it looks more like it belongs to an element before, and not a new paragraph.

Alternatively, put the caption a few pixels below the border of the image and give it a small background or its own border?

**Comment by brotkrueml** [comment]
Actually, IMHO the look of the old rendering is quite good.

**Comment by linawolf** [comment]
I think this should be forwarded to the UX ppl. I always thought the old way didnt have any style and I applied some style.

**Comment by linawolf** [comment]
what is your view on this, [rfoucard](https://github.com/rfoucard)

**Comment by linawolf** [comment]
this is not a bug but an improvement that I made and that you guys approved

**Comment by brotkrueml** [comment]
Then no need to leave this issue open, will add a border to my images manually.
