### ISSUE TITLE
Nested lists can be better styled

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/render-guides#380]
Nested lists look currently that way:

![Bildschirmfoto vom 2024-03-04 12-39-05](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/69ebf861-a8b9-488f-bfac-257e4285809d)

After the last item of the nested list should be more space, perhaps at the beginning less space.

See: https://docs.typo3.org/m/typo3/tutorial-getting-started/12.4/en-us/Installation/ReleaseIntegrity.html#public-keys

**Comment by linawolf** [comment]
Maybe wait with style wishes until after we applied rachels changes from the weekend?

**Comment by brotkrueml** [comment]
Agree, but created the issue, so it is not forgotten.

**Comment by linawolf** [comment]
Ramona is working on this as far as I know

**Comment by linawolf** [comment]
It seems to look better now, so it is probably resoved:

![image](https://github.com/TYPO3-Documentation/render-guides/assets/48202465/8dc3b806-d818-438d-bed8-d5bcbb82af66)
