### ISSUE TITLE
Adjust gap in tabs element between heading and content

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/render-guides#419]
Currently looking like this:

![image](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/4b6704c5-d00e-4d01-a5b6-4c58362a7948)

In the example, the gap between Docker/Podman and the content should be eliminated, so that the heading border is aligned with the content border.

**Comment by linawolf** [comment]
Rachel is working on this as far as I know
