### ISSUE TITLE
Possibly wrong green color used to highlight an element

### ISSUE THREAD

**Issue by soee** [TYPO3-Documentation/render-guides#457]
I'm uncertain whether this is by design or a bug, but on the page https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/Configuration/Index.html, there's a highlighted (green) background element visible. 

It seems unlikely that this highlighting color was intended to be rendered in this way.

**Comment by linawolf** [comment]
thanks for reporting, could you add a screenshot for reference?

**Comment by soee** [comment]
@linawolf sure, here it is:
![image](https://github.com/TYPO3-Documentation/render-guides/assets/1798417/979d4a47-ba7e-4254-ad25-ec7e0588ca6f)

**Comment by linawolf** [comment]
This is resolved, thank you for reporting
