### ISSUE TITLE
confval with :noindex: adjust permalink button

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/render-guides#467]
when the confval directive has the `:noindex:` option it is not a reference target, therefore it cannot be linked directly with the `:confval:` text-role. Adjust the permalink dialoge.

**Comment by brotkrueml** [comment]
I think, noindex is the wrong attribute, as it means it should not be indexed (by search engines). So maybe "noref" would be better.

**Comment by linawolf** [comment]
Noindex is used like that by Sphinx:
https://sphinx-toolbox.readthedocs.io/en/stable/extensions/confval.html#directive-option-confval-noindex

And already implemented by that name in the guides
