### ISSUE TITLE
HTML tags in title are shown escaped

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/render-guides#472]
The documentation section title of the oauth2 extension has HTML, and this is rendered in a broken way:
```
Start / TYPO3 Extension <code class="docutils literal notranslate"><span class="pre">oauth2</span></code> (<code class="docutils literal notranslate"><span class="pre">mfc/oauth2</span></code>)
```

https://docs.typo3.org/p/mfc/oauth2/main/en-us/README.html

![2024-03-25 t3docs oauth2 title](https://github.com/TYPO3-Documentation/render-guides/assets/59036/66a08aba-ae84-4f8e-9148-6a60a393792e)

**Comment by linawolf** [comment]
@cweiske it seems like you are still using the legacy, Sphinx based rendering. I added a test to verify this does not happen in the new rendering. Consider to migrate: https://docs.typo3.org/m/typo3/docs-how-to-document/draft/en-us/WritingDocForExtension/Migrate.html

**Comment by cweiske** [comment]
It's not my extension - I only report the problem I saw.
