### ISSUE TITLE
TYPO3 Exceptions manual not in menu

### ISSUE THREAD

**Issue by fsuter** [TYPO3-Documentation/render-guides#473]
I'm not sure if this is the right place to report this, but the TYPO3 Exceptions manual (https://docs.typo3.org/typo3cms/exceptions/main/en-us/Index.html) does not appear in any navigation element on docs.typo3.org, be it the left-hand menu or the cards on the home page.

I would suggest putting it in the Reference Manuals section, although it shouldn't get too crowded. Maybe a new Troubleshooting section?

**Comment by garvinhicking** [comment]
Good idea; I do think we could add it to "References", something like:

* The [List of Exceptions] shows possible (user-contributed) reasons and solutions for Error Exceptions / Warnings.

@linawolf @brotkrueml

**Comment by brotkrueml** [comment]
Does the exception list in the navigation has a real value?
![image](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/cc8f13c3-74cd-417a-965e-62d6e678159a)

I am with you for indexing them (but the default text on every exception page should be omitted as this clutters the search index a lot). But I am unsure if it has a real value for the user to click through the exception numbers.

**Comment by fsuter** [comment]
I guess I should have been more precise: I was talking about the left-hand menu on the home page, from which I could reach the manual.

I agree that this long listing of exception codes is pretty useless, as long as the search works.

**Comment by linawolf** [comment]
You can use the search with the manual and there are helpfull ressources listed on the left side on how to deal with exceptions...

**Comment by fsuter** [comment]
Well, whatever you decide. My point is mostly that currently this manual is in fact invisible, because it is not indexed and neither linked to in any of the main navigation elements. I stumbled upon it via a Google search.

**Comment by linawolf** [comment]
@fsuter thanks for reporting, We will take it from here

**Comment by linawolf** [comment]
This is solved, it is in the "all documentation" menu
