### ISSUE TITLE
Style horizontal buttons

### ISSUE THREAD

**Issue by garvinhicking** [TYPO3-Documentation/render-guides#474]
Rendertest has this definition:

https://github.com/TYPO3-Documentation/render-guides/blob/main/Documentation-rendertest/ListsAsButtons/Index.rst

When rendered via `make rendertest`, you can see the output in `Documentation-GENERATED-rendertest/ListsAsButtons/Index.html`, which currently looks like this:

<img width="440" alt="Screenshot 2024-03-28 at 15 39 59" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/035ccf83-96a8-420c-ae2b-62e6c916e1e9">
<img width="426" alt="Screenshot 2024-03-28 at 15 40 09" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/4766a2db-73f9-436a-acdd-7a197006b26f">
<img width="443" alt="Screenshot 2024-03-28 at 15 40 17" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/97977ff1-e568-44bb-9c5c-cb04257fdf8c">

This has a few issues:

* It is too colorful
* It has no WCAG AAA rating

So we need to change all the buttons to match a better scheme, also one where we use much less color to convey information. The distinction between all the classes isn't too great, but many docs have used one button or the other.

So we thought to make different attributions look similar, because their intent is similar.

This is what we came up with:

![image](https://github.com/TYPO3-Documentation/render-guides/assets/273326/95bf8941-7c86-4887-9b92-cdf09397e541)

For the warnings we have too ideas; one uses a AA instead of AAA full red display, the other just a border and black text that has AAA then.

If the color scheme like that is ok we can make a PR based on it, and we would also adjust the other buttons we have (search button in the top right, and we'll check for others).

**Comment by garvinhicking** [comment]
@linawolf @rfoucard Do you have thoughts on this?

**Comment by linawolf** [comment]
I would like to use the same color-schme as we do with the admonitions so we don't have two different set of warning color for exampe

**Comment by linawolf** [comment]
I think only using the color on the outline to keep good contrast for the text is a good idea

**Comment by linawolf** [comment]
I think we can reduce the total number of designs to 2or 3 design, similar like with the admonitions. We can then only advertise those and just apply fall back styles to those button designs we dropped

**Comment by fe-hicking** [comment]
@linawolf I thought that's what we did with the colors; which would you replace?

We have these variants:

1: Attention/Primary
2: Important
3: Note/Tip
4: Striking
5: Warning (either A or B, I'm for B)

If we want to reduce that further I'd say:

1: Attention/Primary/Striking (blue background, white text)
2: Note/Tip/Important (blue border, black text)
3: Warning

?

**Comment by rfoucard** [comment]
When do we use buttons in the documentation? 
Do we have concrete example in the actual online documentation?

**Comment by garvinhicking** [comment]
> When do we use buttons in the documentation? 
> 
> Do we have concrete example in the actual online documentation?

docs.s9y.org directly features them:

![image](https://github.com/TYPO3-Documentation/render-guides/assets/273326/ec4fff85-0311-4155-9edb-2f98b527004b)

I'd have to grep the docs for more (only on mobile now)

**Comment by rfoucard** [comment]
thank you!

I have found also other buttons that are in all the pages, and if we try to give them a good contrast, it will be weird, because close to the top menu there is a menu item (that I don't think we can change) with white text in orange background:
![image](https://github.com/TYPO3-Documentation/render-guides/assets/14932950/606169b4-66bd-4525-a872-8c98a99d071e)

so I would go for avoiding as much as possible orange buttons and would go for something like this:
![image](https://github.com/TYPO3-Documentation/render-guides/assets/14932950/a4673ed1-c1c6-430a-8630-5122bb774587)

In the all documentation, I would recommand to: 
- only use light or dark buttons, 
- never underline text in them (even if they are <a> tags), 
- don't use outline versions of them because it is not part of the actual design

**Comment by garvinhicking** [comment]
I've grepped through the uses of our core and external documentations.

All of them utilize these buttons as a normal link button, so we should be good to consolidate this by a lot.

Following the advice @rfoucard I would thus say we do this - please check if that is alright with you and @linawolf then I can talk this over with @fe-breuer next week:

* No underlines in any buttons
* Style the top search button with black text on light grey background. On mouseover, we add a black border around (to indicate a link, using a visual hint like underlines of text links)
* Change mouseover styling for "View Source" and "How to edit" to do the same
* Style the "Edit on github" button to use a black background and white text (because it's a special button we want to put focus on). Mouseover we need something to happen here, I suggest to use black text on white backgruond with a black border then.
* For the "horizbuttons" we change everything down to two classes:
  * `(attention|important|primary|striking|warning)`: black background, white text, mouseover inverted [like "Github" button]
  * `(note|tip)`: light grey background, black text
* Adjust the rendertest to only showcase those two styles (still name all of the legacy names and the m+xxl+xxxl variants, which will all be the same)
* Ensure the buttons on mobile have a proper spacing (i.e. for the "home" listing)

Here are the URLs of the usage cases I've found:

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/Index.html
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Appendix/SettingUpTypo3Ddev.html
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Setup/SetupTypo3.html
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/BugfixingAZ/Index.html
https://docs.typo3.org/Home/Templating.html
https://docs.typo3.org/Home/ConfiguringTYPO3.html
https://docs.typo3.org/Home/UpgradingTYPO3.html
https://docs.typo3.org/Home/CreatingManagingContent.html
https://docs.typo3.org/Home/GettingStarted.html
https://docs.typo3.org/Home/References.html
https://docs.typo3.org/Home/SystemExtensions.html
https://docs.typo3.org/Index.html

https://docs.typo3.org/p/cpsit/typo3-handlebars/0.7/en-us/RenderingConcept/Index.html
https://docs.typo3.org/p/w4services/w4_organization_list/main/en-us/QuickStart/Index.html
https://labor.99grad.de/typo3-docs/typo3-nnrestapi/About/About/50_support.html
https://docs.typo3.org/p/brotkrueml/schema/3.4/en-us/
https://docs.typo3.org/p/georgringer/news/main/en-us/QuickStart/Index.html

And here some images:

<img width="1158" alt="Screenshot 2024-04-02 at 10 37 57" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/2ee31492-48ee-4a02-a367-dc34c8122a85">
<img width="1168" alt="Screenshot 2024-04-02 at 10 37 11" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/70980a04-301e-461d-81b2-024646b88d84">
<img width="826" alt="Screenshot 2024-04-02 at 10 36 43" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/ff22a35e-5ed7-46d1-8792-1a604222623b">
<img width="1179" alt="Screenshot 2024-04-02 at 10 35 36" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/fdbb0d63-d148-458b-b7fb-c6703e027915">
<img width="910" alt="Screenshot 2024-04-02 at 10 35 09" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/503f2f09-1bd5-4fc5-915f-23b262b80f93">
<img width="900" alt="Screenshot 2024-04-02 at 10 31 44" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/e46d590c-7228-4128-94db-dcc0b57045e9">
<img width="1189" alt="Screenshot 2024-04-02 at 10 27 30" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/ad2250c9-c8b7-4893-a2d5-72b91014813a">
<img width="883" alt="Screenshot 2024-04-02 at 10 26 54" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/1e00856e-beaf-44b1-acc5-e1d239bf1e70">
<img width="909" alt="Screenshot 2024-04-02 at 10 26 34" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/7af5cf10-e64a-4b6c-b6b2-61b895831f85">
<img width="1178" alt="Screenshot 2024-04-02 at 10 20 30" src="https://github.com/TYPO3-Documentation/render-guides/assets/273326/00da4cfd-1c73-4887-8161-dbc57789834e">

**Comment by linawolf** [comment]
I would avoid both white on orange and black on orange as both versions are hard to read for some ppl

**Comment by garvinhicking** [comment]
> I would avoid both white on orange and black on orange as both versions are hard to read for some ppl

Yes, that's no longer part of the changes I asked for. The top bar is probably TYPO3 GmbH domain, not sure we should take liberty in styling the last button top right there.

Could you comment on the list of actual changes I asked to perform (don't look at the screenshots, check the text *g*)

**Comment by linawolf** [comment]
sounds good to me
