### ISSUE TITLE
Adjust space around cards

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/render-guides#480]
Cards currently look like:

![image](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/b8883b33-5095-4115-968e-c794769e03c4)

As you see there is on the left side a margin which is not necessary (and I assume, also on the right side).

**Comment by rfoucard** [comment]
Hi Chris,
yes, I will handle this in a patch with other small improvements for this type of content.

**Comment by linawolf** [comment]
One problem I see here is that we have currently no directive used to make cards but we use containers with bootstrap classes on them. So we cannot centrally change classes of containers. It might be a good idea to introduce a directive first

**Comment by linawolf** [comment]
This should be solved when using the new .. cards:: directive, see https://github.com/TYPO3-Documentation/render-guides/issues/514
