### ISSUE TITLE
When hovering over code using `:samp:` pointer is displayed

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/render-guides#481]
When I'm using `:samp:`:

```rst
:samp:`/typo3`
```

Then a pointer is displayed in the browser when hovering over the rendered text:

![samp](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/290271f8-95fe-467a-bc91-bf2d5c2f787c)

This is obviously wrong, as there is nothing to point to, this is no link and nothing happens. It is just inline code, so the default should be used as cursor style.

**Comment by garvinhicking** [comment]
Probably due to the other language popovers, and since this inline code has no specific language variant for it, nothing is shown - we'll need to add an exemption for a 'generic' code in this case.
