### ISSUE TITLE
Definition list: font colour and size not in line with default font

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/render-guides#492]
Using a definition list, for example:

```rst
Sets the number of branches on a page tree to copy.

0
    Branch is *not* copied

1
    Pages on the first level are copied.

2
    Pages on the second level are copied.

And so on.
```

The font size and the font colour are not in line with the default font:

![definition-list](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/833c3c22-dac2-435a-a4a0-feb5defe2099)

**Comment by linawolf** [comment]
The font-colors should be the same now, I was not able to detect a difference in font-size.

**Comment by linawolf** [comment]
Should be resolved in all manuals that have been re-rendered since the  change
