### ISSUE TITLE
Horizontal buttons can be improved

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/render-guides#500]
The horizontal buttons have currently a gaudy color, for example:

![create-a-patch](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/38bffc81-4ae1-4924-bca7-500a47d244b0)
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/BugfixingAZ/Index.html#create-a-patch

As we move with the new rendering to less colorized pages, this may be improved.

**Comment by brotkrueml** [comment]
Sorry, duplicate of #474

**Comment by fe-hicking** [comment]
Thanks though... long easter holidays, my colleague is eager to continue work on it 😅
