### ISSUE TITLE
Regression: Massive whitespace around code block

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/render-guides#509]
With the recent version of render-guides a code block has massive whitespace around the code itself:

![code-block](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/57416346-1496-4932-8b92-3c375366ce08)

Reason for this is:

```css
.code-block {
    padding: 75%;
}
```

It seems it has been introduced recently as the current cersion on docs.typo3.org does not has the problem, only locally rendered with the current render-guides container.

Deactivating the style solves the problem:

![code-block-2](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/69a5e1fe-6cff-4563-ac89-39f597ef257b)

**Comment by brotkrueml** [comment]
Addition: it works correctly with 0.2.37, seems has been introduced with 0.2.38.

**Comment by brotkrueml** [comment]
For a live example see here:
https://docs.typo3.org/m/typo3/reference-tsconfig/12.4/en-us/UserTsconfig/Setup.html

**Comment by fe-hicking** [comment]
Thanks,I noticed this today too and nitified @linawolf who is on the camp today, she might be working on a fix if she's going to present the rendering.

Was caused by this one:

https://github.com/TYPO3-Documentation/render-guides/commit/6b59ff247f5bf83088da8b996d72517bc532b405

**Comment by brotkrueml** [comment]
I wonder why this change was not tested when styles were changed.

**Comment by linawolf** [comment]
It seems like I accidently changed a wrong line and reviewers didn't catch it either.

**Comment by garvinhicking** [comment]
> I wonder why this change was not tested when styles were changed.

Yep, my bad. Had tunnelvision and verified only the header part, and focussed too much on the screenshot.

Also I'm really not a great CSS reviewer, and we're lacking help on frontend related tweaks for the rendering. So many issues open.
