### ISSUE TITLE
php:exception directive -> just an alias for php:class?

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/render-guides#51]

**Comment by linawolf** [comment]
In the sphinx phpdomain world, php:exception is its own directive. Should we just handle it as an alias for php:class or handle it seperately?

**Comment by brotkrueml** [comment]
How it is rendered in the phpdomain world? Different to the class?

**Comment by brotkrueml** [comment]
I assume the directive is there because there is also a text role for referencing it:

    :php:exc:
    Reference an exception. A namespaced name may be used.

https://markstory.github.io/sphinxcontrib-phpdomain/reference.html#role-php-exc

**Comment by linawolf** [comment]
I dont think we have ever used any of this? But the :php:exec: textrole could also just be an alias

**Comment by brotkrueml** [comment]
I don't know if we use this, I don't think so, but we are creating a general package which is a replacement for Sphinx' phpdomain in the PHP world. So we should support this.

**Comment by linawolf** [comment]
This is solved
