### ISSUE TITLE
Improve styles of the Accordion

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/render-guides#512]
Currently the active elements have a strange color and when a h3 is used for the title there is a gab: 

![image](https://github.com/TYPO3-Documentation/render-guides/assets/48202465/86a7a50e-0d4a-45cb-8abf-7c4f66de1d86)

**Comment by tmotyl** [comment]
@linawolf please add a link. Strange color -> you mean the orange?

**Comment by linawolf** [comment]
Solved by https://github.com/TYPO3-Documentation/render-guides/pull/521
