### ISSUE TITLE
Project does not allow case-sensitive filenames for RST/MD files

### ISSUE THREAD

**Issue by garvinhicking** [TYPO3-Documentation/render-guides#53]
Running the command does not find the entrypoint if a filename is called "Index.rst" instead of "index.rst".

Ideally the entrypoint should accept both variants, at least "Index.rst" should be canonical filename, right?

**Comment by jaapio** [comment]
did some trouble shooting together with Garvin, it turns out to be a real OS issue... 

```
<?php

if (file_exists('Documentation/Index.rst')) {
echo "Index.rst exists.\n";
}

if (file_exists('Documentation/index.rst')) {
echo "index.rst exists.\n";
}
```

```
$ php test.php
Index.rst exists.
index.rst exists.
```

we can fix this possibly in guides by handling the index detection in a different way... using `listContents` on the filesystem... which is not very nice... but the only way to cover this.

**Comment by garvinhicking** [comment]
Your help was very productive :) 

Do you want me to make a PR using the listContents method we derived, or are you on it yourself?

**Comment by jaapio** [comment]
Feel free to create a pr, if you need any help let me know.
