### ISSUE TITLE
confval not correctly linked

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/render-guides#540]
Example code:

```rst
.. confval:: some-config
   :name: some-config
```

Linked via

```rst
:confval:`some config <some-config>`
```

Current output:

```html
<a href="#confval-some-config">some config</a>
```

Expected output:

```html
<a href="#some-config">some config</a>
```

The `confval-` prefix in the anchor is wrong.

**Comment by linawolf** [comment]
The `confval-` prefix in HTML is actually needed to prevent duplicate ids on the same page. There can be a section and a confval with the same anchors as they are managed in different categories of references. the id of the confval also hat the `confval-` prefix. There was a dedicated PR to introduce this: https://github.com/phpDocumentor/guides/pull/932

**Comment by brotkrueml** [comment]
But this means, that `:confval:` cannot be used, as it links only to the page and not to the section (as the id for the section is without "confval-" prefix). Then the :confval: role should be removed as it has no value.

**Comment by brotkrueml** [comment]
This is a bug: linking to a confval via `:confval:` does not work!

**Comment by linawolf** [comment]
Sorry about that didnt get that from your initial report. I will check on that
