### ISSUE TITLE
Duplicate namespace in CoreApi Reference documentation

### ISSUE THREAD

**Issue by mavolkmer** [TYPO3-Documentation/render-guides#551]
This is an issue about a misbehaviour of codesnippet namespace rendering.

first discovered on: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/Extbase/Reference/UriBuilder.html#uri-builder-api
other ApiDoc are also affected like `RepositoryApi` so probably a general problem

**Current behaviour**
```
Fully qualified name: \TYPO3\CMS\Extbase\Mvc\Web\Routing\TYPO3\CMS\Extbase\Mvc\Web\Routing
```

**Expected behaviour**
```
Fully qualified classname: \TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder
```
or
```
Fully qualified namespace: \TYPO3\CMS\Extbase\Mvc\Web\Routing
```

I am sorry to not offer a pr directly but I am not that deep into documentation-technology but hopefully someone with deeper knowledge can find the matching sourcecode quickly.

**Comment by linawolf** [comment]
Thanks for reporting, I will investigate. Recently made some changes here
