### ISSUE TITLE
Style command lists

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/render-guides#559]
An example can currently be found in Documentation-rendertest/ConsoleCommands

![image](https://github.com/TYPO3-Documentation/render-guides/assets/48202465/c7fabda3-adb8-47ba-a90f-1a578c932c9a)

**Comment by linawolf** [comment]
http://localhost:63342/render-guides/Documentation-GENERATED-rendertest/ConsoleCommands/Index.html

**Comment by Tim-Obert** [comment]
Is resolved by #809
