### ISSUE TITLE
Style PHP domain objects

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/render-guides#560]
Example in Documentation-rendertest/PhpDomain

![image](https://github.com/TYPO3-Documentation/render-guides/assets/48202465/92199d37-fd0e-4b09-b306-e21c95f5c79e)

These styles use colors that are used nowhere else. Decide how to display parameter lists etc

**Comment by mouflondarko** [comment]
![obraz](https://github.com/user-attachments/assets/95ec4c18-6833-4d84-819a-5e03742eda0e)
Got rid of some background colors & used a different (existing in other places) color for keywords, also decreased font size a bit to make whole section easier to read

As discussed with @linawolf this proposal needs more work to avoid using many colors in text (possibly replace the blue color with gray + experiment with gray tones for parameters or try to emphasize the keyword using a background/decoration)

**Comment by linawolf** [comment]
I think using dark grey would be fine

**Comment by linawolf** [comment]
@mouflondarko are you still working on this?

**Comment by linawolf** [comment]
@Tim-Obert while you are at it, could you also solve this and make it look alike with the confvals?

**Comment by linawolf** [comment]
@mouflondarko no need, tim will take over as he is working on related topics anyway
