### ISSUE TITLE
Improve menues with many levels and longer titles

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/render-guides#562]
For exampe https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Backend/JavaScript/RequireJS/Extensions/Index.html

![image](https://github.com/TYPO3-Documentation/render-guides/assets/48202465/d598f103-9097-476d-9abd-2478474528a2)

Compare with the old menu (we dont want orange back for accessibility reasons) but there was more space and it looked more tidy:
https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/

![image](https://github.com/TYPO3-Documentation/render-guides/assets/48202465/9d012d67-9728-4b0c-bfdb-289d164849a4)

**Comment by tmotyl** [comment]
related: https://github.com/TYPO3-Documentation/render-guides/issues/229
