### ISSUE TITLE
Improve the visibility of file reference styling in tables

### ISSUE THREAD

**Issue by Alagts** [TYPO3-Documentation/render-guides#567]
**Issue description:** 
For example under this [link](https://docs.typo3.org/p/friendsoftypo3/extension-builder/main/en-us/GraphicalEditor/Index.html#2-insert-meta-data-of-extension) I recognized that the file reference styling is almost not visible since the table row background has the same color as the file reference background color - see screenshot. 

![file_styling](https://github.com/TYPO3-Documentation/render-guides/assets/16323871/65d7c0cc-a41f-4ee5-9925-0a4aba86c39a)

Here is the source code: 
[source code link](https://docs.typo3.org/p/friendsoftypo3/extension-builder/main/en-us/_sources/GraphicalEditor/Index.rst.txt)

**Suggestion:** 
I would suggest to use white as background color for every uneven row, as for every uneven number the background of the row is light grey. And not visible in a light grey row. Or I would suggest to use another background color for file references in tables - for example a color darker than the current color, since we want to be able to see the file reference in white (even) and light grey (uneven) table rows.

**Comment by linawolf** [comment]
Right, I think Jaapio fixed this
