### ISSUE TITLE
Links from the names of languages in the menu

### ISSUE THREAD

**Issue by aksenovaa** [TYPO3-Documentation/render-guides#640]
Now in the menu on the left side there are Languages for localised documents (Russian, French), below there are links to versions of documents for these languages.
This is a bit confusing. It would be good to link from the language name to the latest version of the documentation for that language.
![image](https://github.com/user-attachments/assets/6a655ffe-3299-4f03-8198-ef5c3f181dbf)

**Comment by garvinhicking** [comment]
We could link the name of the language with the latest version of that language, that should be possible!

**Comment by aksenovaa** [comment]
Yeah, that's what it takes
