### ISSUE TITLE
Rendering issue with extension versions

### ISSUE THREAD

**Issue by s2b** [TYPO3-Documentation/render-guides#694]
If an extension releases version 1.10 (2 digits as minor version), with the new rendering the second digit is missing both in the overview and in the selected item in the version switcher.

Example: https://docs.typo3.org/p/praetorius/vite-asset-collector/1.10/en-us/

Garvin says: Probably float casting-related?

**Comment by garvinhicking** [comment]
Closing issue as this applies to `guides`, which in turn boils down to symfony/config::XmlUtils which in turn boils down to `phpize`.

I'll open an issue in the `guides` projects and it will be linked here.
