### ISSUE TITLE
Use "Line Break Opportunity" tags in confvals

### ISSUE THREAD

**Issue by mouflondarko** [TYPO3-Documentation/render-guides#719]
[The Line Break Opportunity tag (`<wbr>`)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) could be used in order to achieve more control over word wrapping inside confvals. As suggested in PR #718 an automatic formatter could be used to put `<wbr>` tags where necessary (e.g. before a dot or dash). Such formatter would further allow to improve wrapping in other places.

An example of `<wbr>` tag in action:
1. without tags (+ `word-wrap: anywhere`)
    ```html
    email.templateRootPaths
    exposeNonexistentUserInForgotPasswordDialog
    ```
    ![obraz](https://github.com/user-attachments/assets/187baad6-74ac-4c4a-8906-b244e4b21013)

2. with tags (+ `word-wrap: anywhere`)
    ```html
    email<wbr>.templateRootPaths
    expose<wbr>Nonexistent<wbr>User<wbr>In<wbr>Forgot<wbr>Password<wbr>Dialog
    ```
    ![obraz](https://github.com/user-attachments/assets/f8dee443-e022-4994-b87e-9c7903a11655)

**Comment by garvinhicking** [comment]
Logic idea:

```
$string = preg_replace('/([A-Z\.])/i', '<wbr>\1', $string);
```

that would add a '<wbr>' tag before any uppercase character and before any dot... (untested)

**Comment by linawolf** [comment]
I would add it between lowercase letter followed by uppercase as this prevents breking SOME_LONG_CONSTANT in akward places
