### ISSUE TITLE
Check how/if --input-file argument is broken

### ISSUE THREAD

**Issue by garvinhicking** [TYPO3-Documentation/render-guides#77]
"According to the help this command should be possible:
vendor/bin/guides --output=tests/Integration/tests/php/enum-namespace-directive/expected --input-file=tests/Integration/tests/php/enum-namespace-directive/input/index.rst
But I get the error:
File at path index.rst does not exist
The input file exists, copied the path via PhpStorm directly.
What is wrong?"

**Comment by linawolf** [comment]
Ill have a look after work

**Comment by garvinhicking** [comment]
I checked this out now. The misconception (missing documentation?) seems to be that --input-file specifies the ENTRY ROOT of the selected input directory.

So in your case this might work:

```
vendor/bin/guides --output=tests/Integration/tests/php/enum-namespace-directive/expected --input-file=index.rst tests/Integration/tests/bignum/bignum-lists/input
```
(Specify the input directory as an argument-less option, and only specify the filename as input-file)

The documentation on this has been improved via: https://github.com/garvinhicking/guides/commit/d0ce573a2129af6e15a9f53c34d2ebf6745c4d1b
