### ISSUE TITLE
project_issues should also allow bitbucket

### ISSUE THREAD

**Issue by liayn** [TYPO3-Documentation/render-guides#795]
> Output format html: Rendering: //Index.html[2024-10-19T20:52:21.293992+00:00] app.WARNING: For security reasons only only "project_issues" links in the guides.xml to one of these 3 plattforms are allowed: https://forge.typo3.org/ https://github.com/ https://gitlab.com/ [] []

We run https://extensions.typo3.org/extension/rx_shariff on bitbucket. And to avoid user hassle, we currently do not intend to migrate this to some of the mentioned platforms.

**Comment by linawolf** [comment]
sovled
