### ISSUE TITLE
Search through the Project locally

### ISSUE THREAD

**Issue by bp-nkrause** [TYPO3-Documentation/render-guides#800]
Hello,
is there a way to use the search locally in my DDEV setup? I also want the search to only search my current project, how is that possible?

**Comment by garvinhicking** [comment]
Thanks for getting in touch :) 

That's sadly not possible currently. It would need its own indexing, which the project does server-side with external software (solr). Sadly this will be beyond scope for this project to provide, thus I'm closing the issue for now.

(for local search you could either spin up your own solr-instance or maybe better use file-based indexing within IDEs that can parse the HTML files stored on-disc)
