### ISSUE TITLE
Sidebar navigation is not opened when a Document within subdirectory is rendered

### ISSUE THREAD

**Issue by garvinhicking** [TYPO3-Documentation/render-guides#81]
Steps to reproduce:
* Render "Documentation" of repository
* Check a subpage like `Developers/Building/Index.html`
* Left navigation shows the menu state just like for the root `Index.html`

Expected output: 
* The menu should show the entries of "Developers" opened up directly

**Comment by linawolf** [comment]
duplicate of https://github.com/TYPO3-Documentation/render-guides/issues/222
