### ISSUE TITLE
Shown Permalink is not valid

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Documentation/render-guides#832]
### Current behavior

I wanted to send a link to a specific part of typoscript reference guide to a TYPO3 friend. The shown/copied permalink https://docs.typo3.org/permalink/t3tsref:confval-page-includecsslibs results in an invalid shortcode after opening the permalink.

### Expected behavior/output

the permalink should work and https://docs.typo3.org/m/typo3/reference-typoscript/13.4/en-us/TopLevelObjects/Page/Index.html#confval-page-includecsslibs must open

**Comment by linawolf** [comment]
Sorry about that, we fixed them
